version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: volcengine-backend
    env_file:
      - .env
    volumes:
      - ./backend/app/data:/app/data
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: volcengine-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
