# Docker Compose configuration for Fullstack Single Image
# This runs both frontend and backend in a single container

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.fullstack
      args:
        - NODE_VERSION=20
        - PYTHON_VERSION=3.11
    image: volcengine-fullstack:latest
    container_name: volcengine-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend/app/data:/app/data
    ports:
      - "3000:80"
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:80/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
